[workspace]
resolver = "2"
members = [
    "crates/ir",
    "crates/codegen",
    "crates/parser",
    "crates/filecheck",
    "crates/triple",
    "crates/macros",
    "crates/interpreter",
    "crates/verifier",
]

[workspace.package]
edition = "2024"
